# Proprietes de l'application
spring:
  application:
    name: membrescompetitionsservice # nom de l'application
  cloud:
    # Activation remontée management dans Eureka
    config:
      service-registry:
        auto-registration:
          register-management: on
  # configuration lien vers serveur Zipkin
  zipkin:
    # SANS DOCKER COMPOSE
    #baseurl: http://localhost:9411/
    # SANS DOCKER COMPOSE
    baseurl: http://odrzipkin:9411/
    sender:
      type: web # les requêtes seront envoyés en HTTP
  # Configuration de Sleuth
  sleuth:
    sampler:
      probability: 1.0
# Activation des endpoints pour le monitoring
management:
  endpoints:
    web:
      exposure:
        include:
          env,health,
          info,metrics,
          loggers,mappings, prometheus
# Configuration client de l'annuaire
# Le serveur clients-comptes va s'enregistrer comme un micro-service sur l'annuaire
eureka:
  client:
    serviceUrl:
      # SANS DOCKER COMPOSE
      # defaultZone: http://localhost:10001/eureka/ # url d'accès à l'annuaire
      # AVEC DOCKER COMPOSE
      defaultZone: http://odrannuaire:10001/eureka/ # url d'accès à l'annuaire

  # Ajout métadonnée dans Eureka pour que Prometheus puisse déterminer le chemin vers les métriques
  instance:
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${management.server.port}"
# Configuration du log.
logging:
  level:
    org.springframework.web: INFO # Choix du niveau de log affiché

# Proprietes du serveur d'entreprise
server:
  port: 10051   # HTTP (Tomcat) port